name: addpost
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 
  firebase_core: 
  get: ^4.6.6
  cloud_firestore: ^5.4.0 
  extended_image: ^8.2.4 
  flutter_svg: ^2.0.10+1 
  flick_video_player: ^0.5.0
  audioplayers: ^5.1.0
  firebase_storage: ^12.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  dio: ^5.7.0
  video_thumbnail: ^0.5.0
  video_compress: 




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/font/Gilroy-Bold.ttf
